### ISSUE TITLE
Code enhancement? 

### ISSUE THREAD

**Issue by christpa** [ammegandchips/PACE_Paternal_BMI#2]
I would suggest to use the function cut() instead of the extensive re-labeling done from line: 103 to 124. Below is a short example of how you would do this in one line: 
```
bmi <- round(rnorm(100,26, 4),1) ## Just to give some values, omitted in the script
factor(cut(bmi, c(min(bmi)-1,18.5,25,30, max(bmi))), labels = c("underweight","normal","overweight", "obese")) ## The actual relabeling
```

**Comment by ammegandchips** [comment]
Thanks Christian -  I didn't know about the cut() function, but clearly it's going to change my life :)
Since it does exactly the same as my messy code, but some cohorts have already got started using that, I think I'll leave the code as it is for this project - unless I end up having to change more stuff due to further issues ;) Thanks again!

**Comment by christpa** [comment]
We all live and learn :-)
